"""Adiciona UniqueConstraint na tabela datasus

Revision ID: 06020edc60a7
Revises: 47b546133f37
Create Date: 2025-11-04 05:53:11.239740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06020edc60a7'
down_revision: Union[str, Sequence[str], None] = '47b546133f37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('_mortes_municipio_ano_mes_dt'), 'datasus', type_='unique')
    op.create_unique_constraint('_municipio_ano_mes_dt', 'datasus', ['municipio', 'ano', 'mes'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_municipio_ano_mes_dt', 'datasus', type_='unique')
    op.create_unique_constraint(op.f('_mortes_municipio_ano_mes_dt'), 'datasus', ['mortes', 'municipio', 'ano', 'mes'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
