"""adicionando a coluna uf

Revision ID: 25b44c90b5e9
Revises: 9ceab160349c
Create Date: 2025-10-30 18:32:26.939286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25b44c90b5e9'
down_revision: Union[str, Sequence[str], None] = '9ceab160349c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eventos', sa.Column('uf', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('eventos', 'uf')
    # ### end Alembic commands ###
