"""criacao do banco

Revision ID: 37e14cb87c7a
Revises: 8ec7ddb86ded
Create Date: 2025-11-11 21:59:08.850841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37e14cb87c7a'
down_revision: Union[str, Sequence[str], None] = '8ec7ddb86ded'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comparativo_previsoes', sa.Column('id_x', sa.Integer(), nullable=False))
    op.add_column('comparativo_previsoes', sa.Column('id_y', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_comparativo_previsoes_id_x'), 'comparativo_previsoes', ['id_x'], unique=False)
    op.create_index(op.f('ix_comparativo_previsoes_id_y'), 'comparativo_previsoes', ['id_y'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comparativo_previsoes_id_y'), table_name='comparativo_previsoes')
    op.drop_index(op.f('ix_comparativo_previsoes_id_x'), table_name='comparativo_previsoes')
    op.drop_column('comparativo_previsoes', 'id_y')
    op.drop_column('comparativo_previsoes', 'id_x')
    # ### end Alembic commands ###
