"""Adiciona UniqueConstraint na tabela datasus

Revision ID: 47b546133f37
Revises: 92f15b4ff383
Create Date: 2025-11-04 05:46:27.898789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47b546133f37'
down_revision: Union[str, Sequence[str], None] = '92f15b4ff383'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_mortes_municipio_ano_mes_dt', 'datasus', ['mortes', 'municipio', 'ano', 'mes'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_mortes_municipio_ano_mes_dt', 'datasus', type_='unique')
    # ### end Alembic commands ###
