"""criacao do banco

Revision ID: 8ec7ddb86ded
Revises: 
Create Date: 2025-11-11 21:54:21.182414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ec7ddb86ded'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comparativo_previsoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('municipio', sa.String(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('total_vitimas_ano', sa.Integer(), nullable=False),
    sa.Column('previsao_homicidios', sa.Float(), nullable=False),
    sa.Column('previsao_min', sa.Float(), nullable=False),
    sa.Column('previsao_max', sa.Float(), nullable=False),
    sa.Column('classificacao', sa.String(), nullable=False),
    sa.Column('margem_erro_k', sa.Float(), nullable=True),
    sa.Column('correlacao_temporal_r', sa.Float(), nullable=True),
    sa.Column('erro_padrao_se', sa.Float(), nullable=True),
    sa.Column('fator_penalidade_fr', sa.Float(), nullable=True),
    sa.Column('n_anos_dados', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('municipio', 'ano', name='_municipio_ano_comparativo_uc')
    )
    op.create_index(op.f('ix_comparativo_previsoes_ano'), 'comparativo_previsoes', ['ano'], unique=False)
    op.create_index(op.f('ix_comparativo_previsoes_classificacao'), 'comparativo_previsoes', ['classificacao'], unique=False)
    op.create_index(op.f('ix_comparativo_previsoes_id'), 'comparativo_previsoes', ['id'], unique=False)
    op.create_index(op.f('ix_comparativo_previsoes_municipio'), 'comparativo_previsoes', ['municipio'], unique=False)
    op.create_table('dados_reais_anuais',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('municipio', sa.String(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('total_vitimas_ano', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('municipio', 'ano', name='_municipio_ano_reais_uc')
    )
    op.create_index(op.f('ix_dados_reais_anuais_ano'), 'dados_reais_anuais', ['ano'], unique=False)
    op.create_index(op.f('ix_dados_reais_anuais_id'), 'dados_reais_anuais', ['id'], unique=False)
    op.create_index(op.f('ix_dados_reais_anuais_municipio'), 'dados_reais_anuais', ['municipio'], unique=False)
    op.create_table('datasus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('municipio', sa.String(), nullable=False),
    sa.Column('mes', sa.String(), nullable=False),
    sa.Column('mortes', sa.Integer(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('municipio', 'ano', 'mes', name='_municipio_ano_mes_dt')
    )
    op.create_index(op.f('ix_datasus_id'), 'datasus', ['id'], unique=False)
    op.create_table('previsoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('municipio', sa.String(), nullable=False),
    sa.Column('ano_previsao', sa.Integer(), nullable=False),
    sa.Column('previsao_homicidios', sa.Integer(), nullable=False),
    sa.Column('previsao_min', sa.Integer(), nullable=False),
    sa.Column('previsao_max', sa.Integer(), nullable=False),
    sa.Column('n_anos_dados', sa.Integer(), nullable=False),
    sa.Column('margem_erro_k', sa.Float(), nullable=True),
    sa.Column('correlacao_temporal_r', sa.Float(), nullable=True),
    sa.Column('erro_padrao_se', sa.Float(), nullable=True),
    sa.Column('fator_penalidade_fr', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('municipio', 'ano_previsao', name='_municipio_ano_uc')
    )
    op.create_index(op.f('ix_previsoes_ano_previsao'), 'previsoes', ['ano_previsao'], unique=False)
    op.create_index(op.f('ix_previsoes_id'), 'previsoes', ['id'], unique=False)
    op.create_index(op.f('ix_previsoes_municipio'), 'previsoes', ['municipio'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_previsoes_municipio'), table_name='previsoes')
    op.drop_index(op.f('ix_previsoes_id'), table_name='previsoes')
    op.drop_index(op.f('ix_previsoes_ano_previsao'), table_name='previsoes')
    op.drop_table('previsoes')
    op.drop_index(op.f('ix_datasus_id'), table_name='datasus')
    op.drop_table('datasus')
    op.drop_index(op.f('ix_dados_reais_anuais_municipio'), table_name='dados_reais_anuais')
    op.drop_index(op.f('ix_dados_reais_anuais_id'), table_name='dados_reais_anuais')
    op.drop_index(op.f('ix_dados_reais_anuais_ano'), table_name='dados_reais_anuais')
    op.drop_table('dados_reais_anuais')
    op.drop_index(op.f('ix_comparativo_previsoes_municipio'), table_name='comparativo_previsoes')
    op.drop_index(op.f('ix_comparativo_previsoes_id'), table_name='comparativo_previsoes')
    op.drop_index(op.f('ix_comparativo_previsoes_classificacao'), table_name='comparativo_previsoes')
    op.drop_index(op.f('ix_comparativo_previsoes_ano'), table_name='comparativo_previsoes')
    op.drop_table('comparativo_previsoes')
    # ### end Alembic commands ###
