"""Adiciona UniqueConstraint na tabela eventos

Revision ID: 92f15b4ff383
Revises: 25b44c90b5e9
Create Date: 2025-10-30 20:27:18.290462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92f15b4ff383'
down_revision: Union[str, Sequence[str], None] = '25b44c90b5e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_uf_municipio_ano_mes_uc', 'eventos', ['uf', 'municipio', 'ano', 'mes'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_uf_municipio_ano_mes_uc', 'eventos', type_='unique')
    # ### end Alembic commands ###
