"""Corrige PK da tabela eventos para id

Revision ID: 9ceab160349c
Revises: 
Create Date: 2025-10-25 04:43:17.920556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ceab160349c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datasus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('municipio', sa.String(), nullable=False),
    sa.Column('mes', sa.String(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('mortes', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_datasus_id'), 'datasus', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_datasus_id'), table_name='datasus')
    op.drop_table('datasus')
    # ### end Alembic commands ###
