"""criando as tabelas do banco

Revision ID: d17f7a133bf8
Revises: 
Create Date: 2026-05-04 20:01:13.230850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd17f7a133bf8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('municipios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('uf', sa.String(length=2), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome', 'uf', name='_municipio_nome_uf_uc')
    )
    op.create_index(op.f('ix_municipios_id'), 'municipios', ['id'], unique=False)
    op.create_index(op.f('ix_municipios_nome'), 'municipios', ['nome'], unique=False)
    op.create_table('dados_reais_anuais',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('municipio_id', sa.Integer(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('total_vitimas_ano', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['municipio_id'], ['municipios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('municipio_id', 'ano', name='_municipio_id_ano_reais_uc')
    )
    op.create_index(op.f('ix_dados_reais_anuais_ano'), 'dados_reais_anuais', ['ano'], unique=False)
    op.create_index(op.f('ix_dados_reais_anuais_id'), 'dados_reais_anuais', ['id'], unique=False)
    op.create_index(op.f('ix_dados_reais_anuais_municipio_id'), 'dados_reais_anuais', ['municipio_id'], unique=False)
    op.create_table('datasus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('municipio_id', sa.Integer(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('mortes', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['municipio_id'], ['municipios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('municipio_id', 'ano', 'mes', name='_datasus_municipio_ano_mes_uc')
    )
    op.create_index(op.f('ix_datasus_id'), 'datasus', ['id'], unique=False)
    op.create_index(op.f('ix_datasus_municipio_id'), 'datasus', ['municipio_id'], unique=False)
    op.create_table('eventos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('municipio_id', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('vitimas', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['municipio_id'], ['municipios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('municipio_id', 'ano', 'mes', name='_municipio_id_ano_mes_uc')
    )
    op.create_index(op.f('ix_eventos_ano'), 'eventos', ['ano'], unique=False)
    op.create_index(op.f('ix_eventos_id'), 'eventos', ['id'], unique=False)
    op.create_index(op.f('ix_eventos_municipio_id'), 'eventos', ['municipio_id'], unique=False)
    op.create_table('previsoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('municipio_id', sa.Integer(), nullable=False),
    sa.Column('ano_previsao', sa.Integer(), nullable=False),
    sa.Column('previsao_homicidios', sa.Integer(), nullable=False),
    sa.Column('previsao_min', sa.Integer(), nullable=False),
    sa.Column('previsao_max', sa.Integer(), nullable=False),
    sa.Column('n_anos_dados', sa.Integer(), nullable=False),
    sa.Column('margem_erro_k', sa.Float(), nullable=True),
    sa.Column('correlacao_temporal_r', sa.Float(), nullable=True),
    sa.Column('erro_padrao_se', sa.Float(), nullable=True),
    sa.Column('fator_penalidade_fr', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['municipio_id'], ['municipios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('municipio_id', 'ano_previsao', name='_municipio_id_ano_previsao_uc')
    )
    op.create_index(op.f('ix_previsoes_ano_previsao'), 'previsoes', ['ano_previsao'], unique=False)
    op.create_index(op.f('ix_previsoes_id'), 'previsoes', ['id'], unique=False)
    op.create_index(op.f('ix_previsoes_municipio_id'), 'previsoes', ['municipio_id'], unique=False)
    op.create_table('comparativo_previsoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('previsao_id', sa.Integer(), nullable=False),
    sa.Column('dado_real_id', sa.Integer(), nullable=True),
    sa.Column('municipio_id', sa.Integer(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('total_vitimas_ano', sa.Integer(), nullable=True),
    sa.Column('previsao_homicidios', sa.Float(), nullable=False),
    sa.Column('previsao_min', sa.Float(), nullable=False),
    sa.Column('previsao_max', sa.Float(), nullable=False),
    sa.Column('classificacao', sa.String(), nullable=False),
    sa.Column('margem_erro_k', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['dado_real_id'], ['dados_reais_anuais.id'], ),
    sa.ForeignKeyConstraint(['municipio_id'], ['municipios.id'], ),
    sa.ForeignKeyConstraint(['previsao_id'], ['previsoes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('municipio_id', 'ano', name='_municipio_id_ano_comparativo_uc')
    )
    op.create_index(op.f('ix_comparativo_previsoes_ano'), 'comparativo_previsoes', ['ano'], unique=False)
    op.create_index(op.f('ix_comparativo_previsoes_classificacao'), 'comparativo_previsoes', ['classificacao'], unique=False)
    op.create_index(op.f('ix_comparativo_previsoes_id'), 'comparativo_previsoes', ['id'], unique=False)
    op.create_index(op.f('ix_comparativo_previsoes_municipio_id'), 'comparativo_previsoes', ['municipio_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comparativo_previsoes_municipio_id'), table_name='comparativo_previsoes')
    op.drop_index(op.f('ix_comparativo_previsoes_id'), table_name='comparativo_previsoes')
    op.drop_index(op.f('ix_comparativo_previsoes_classificacao'), table_name='comparativo_previsoes')
    op.drop_index(op.f('ix_comparativo_previsoes_ano'), table_name='comparativo_previsoes')
    op.drop_table('comparativo_previsoes')
    op.drop_index(op.f('ix_previsoes_municipio_id'), table_name='previsoes')
    op.drop_index(op.f('ix_previsoes_id'), table_name='previsoes')
    op.drop_index(op.f('ix_previsoes_ano_previsao'), table_name='previsoes')
    op.drop_table('previsoes')
    op.drop_index(op.f('ix_eventos_municipio_id'), table_name='eventos')
    op.drop_index(op.f('ix_eventos_id'), table_name='eventos')
    op.drop_index(op.f('ix_eventos_ano'), table_name='eventos')
    op.drop_table('eventos')
    op.drop_index(op.f('ix_datasus_municipio_id'), table_name='datasus')
    op.drop_index(op.f('ix_datasus_id'), table_name='datasus')
    op.drop_table('datasus')
    op.drop_index(op.f('ix_dados_reais_anuais_municipio_id'), table_name='dados_reais_anuais')
    op.drop_index(op.f('ix_dados_reais_anuais_id'), table_name='dados_reais_anuais')
    op.drop_index(op.f('ix_dados_reais_anuais_ano'), table_name='dados_reais_anuais')
    op.drop_table('dados_reais_anuais')
    op.drop_index(op.f('ix_municipios_nome'), table_name='municipios')
    op.drop_index(op.f('ix_municipios_id'), table_name='municipios')
    op.drop_table('municipios')
    # ### end Alembic commands ###
