# Generated by Django 5.2.1 on 2025-05-24 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome completo *')),
                ('instituicao', models.CharField(help_text='Registre a instituição, ou universidade, ou empresa', max_length=50, verbose_name='Instituição a que pertence *')),
                ('email', models.EmailField(db_index=True, max_length=100, unique=True, verbose_name='Email')),
                ('celular', models.CharField(help_text='Use DDD, por exemplo 55987619832', max_length=14, verbose_name='Número celular com DDD *')),
                ('cpf', models.CharField(help_text='ATENÇÃO: Somente os NÚMEROS', max_length=14, verbose_name='CPF *')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
